version: '3'

services:
    nginx:
        container_name: hintify-nginx
        image: nginx
        ports:
            - '80:80'
        links:
            - phpfpm
        volumes:
            - ./:/var/www
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
            - ./docker/logs/access.log:/var/log/nginx/access.log
            - ./docker/logs/error.log:/var/log/nginx/error.log

    phpfpm:
        build:
            context: .
            dockerfile: ./docker/phpfpm.docker
        container_name: hintify-php
        image: hintify/php
        ports:
            - '9000:9000'
        volumes:
            - ./:/var/www

    mysql:
        container_name: hintify-mysql
        image: mariadb
        ports:
            - '3306:3306'
        volumes:
            - ./docker/db-data:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=blink
            - MYSQL_USER=bildadmin
            - MYSQL_PASSWORD=secret

    nodejs:
        container_name: hintify-nodejs
        image: node:10
        volumes:
            - ./:/app
        working_dir: /app
